spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener
spring.datasource.username=root
spring.datasource.password=Naga@2609

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080